#!/bin/zsh

############################################
# Bootstrap scripts for installed software #
############################################

# Vim command line software
export VIMINIT="source ${HOME}/.dotfiles/.vimrc"

# VSCode
if [[ ! -f $HOME/Library/Application\ Support/Code/User/settings.json ]]; then
    ln -s \
        "${HOME}/.dotfiles/.vscode/settings.json" \
        "${HOME}/Library/Application Support/Code/User/settings.json"
;fi

# Vim Extension for VSCode (MacBook Air)
defaults write com.microsoft.VSCode ApplePressAndHoldEnabled         -bool false  # For VS Code
defaults write com.microsoft.VSCodeInsiders ApplePressAndHoldEnabled -bool false  # For VS Code Insider
defaults write com.vscodium ApplePressAndHoldEnabled                 -bool false  # For VS Codium

# git global ignore
hash git &>/dev/null \
    && git config --global core.excludesFile "${HOME}/.dotfiles/.gitignore_global"
