#!/bin/zsh

###########################################
# Command line path to installed software #
###########################################

# {{{ brew
export PATH=${PATH}:/opt/homebrew/bin
# }}}

# {{{ asdf
if [ -f "/opt/homebrew/opt/asdf/libexec/asdf.sh" ]; then . /opt/homebrew/opt/asdf/libexec/asdf.sh; fi
# }}}


# {{{ rust / cargo
export PATH=${PATH}:$HOME/.cargo/bin
# }}}

# {{{ go
export GOPATH=${HOME}/proj/go
export PATH=${PATH}:${GOPATH}/bin
# }}}

# {{{ uv (~/.local/bin)
export PATH="$HOME/.local/bin:$PATH"
# }}}

# {{{ asdf
export PATH="${ASDF_DATA_DIR:-$HOME/.asdf}/shims:$PATH"
# }}}

# {{{ VS Code `code` command, if Visual Studio Code is installed
if [ -d "/Applications/Visual Studio Code.app/Contents/Resources/app/bin" ]; then
  export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
else
  echo "Visual Studio Code is not installed"
fi
# }}}

# {{{ Google Cloud SDK.
if [ -f "$HOME/.google-cloud-sdk/path.zsh.inc" ]; then . "$HOME/.google-cloud-sdk/path.zsh.inc"; fi
if [ -f "$HOME/.google-cloud-sdk/completion.zsh.inc" ]; then . "$HOME/.google-cloud-sdk/completion.zsh.inc"; fi
# }}}
