#!/bin/zsh

###########################################
# Command line path to installed software #
###########################################

# {{{ brew
export PATH=${PATH}:/opt/homebrew/bin
# }}}

# {{{ gvm
[[ -s "${HOME}/.gvm/scripts/gvm" ]] && source "${HOME}/.gvm/scripts/gvm"
# }}}

# {{{ nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
# }}}

# {{{ VS Code `code` command, if Visual Studio Code is installed
if [ -d "/Applications/Visual Studio Code.app/Contents/Resources/app/bin" ]; then
  export PATH="$PATH:/Applications/Visual Studio Code.app/Contents/Resources/app/bin"
else
  echo "Visual Studio Code is not installed"
fi
# }}}

# {{{ Google Cloud SDK.
if [ -f "/Users/${USER}/.google-cloud-sdk/path.zsh.inc"       ]; then . "/Users/${USER}/.google-cloud-sdk/path.zsh.inc"      ; fi
if [ -f "/Users/${USER}/.google-cloud-sdk/completion.zsh.inc" ]; then . "/Users/${USER}/.google-cloud-sdk/completion.zsh.inc"; fi
# }}}
